export const columns = [
	{
		title: '公告标题',
		dataIndex: 'title',
		key: 'title',
		checked: true,
		type: 'input',
		fixed: 'left',
		width: 200,
	},
	{
		title: '公告内容',
		noShow: true,
		dataIndex: 'context',
		key: 'context',
		type: 'input',
	},
	{
		title: '附件',
		noShow: true,
		dataIndex: 'fileUrl',
		key: 'fileUrl',
		type: 'date',
	},
	{
		title: '发布时间',
		noShow: true,
		dataIndex: 'pushTime',
		key: 'pushTime',
		width: 200,
		type: 'input',
	},
	{
		title: '发布截止日期',
		noShow: true,
		dataIndex: 'expirationTime',
		key: 'expirationTime',
		width: 200,
		type: 'input',
	},
	{
		title: '当前状态',
		noShow: true,
		dataIndex: 'state',
		key: 'state',
		type: 'select',
	},
	{
		title: '发布人',
		dataIndex: 'publisherName',
		noShow: true,
		key: 'publisherName',
		type: 'input',
	},
];
