export const columns = [
	{
		title: 'IP',
		dataIndex: 'ip',
		key: 'ip',
		checked: true,
		type: 'input',
		fixed: 'left',
		width: 200,
	},
	{
		title: '防护动作',
		dataIndex: 'listRegistrationAction',
		key: 'listRegistrationAction',
		checked: true,
		type: 'select',
	},
	{
		title: '地址',
		dataIndex: 'listRegistrationAddress',
		key: 'listRegistrationAddress',
		noShow: true,
		type: 'input',
	},
	{
		title: '原因',
		dataIndex: 'remark',
		key: 'remark',
		noShow: true,
		type: 'input',
	},
	{
		title: '生效时间',
		dataIndex: 'takeEffectTime',
		noShow: true,
		key: 'takeEffectTime',
		width: 200,
		type: 'date',
	},
	{
		title: '状态',
		dataIndex: 'listRegistrationStatus',
		key: 'listRegistrationStatus',
		checked: true,
		type: 'select',
	},
	{
		title: '防护次数',
		dataIndex: 'interceptFrequency',
		noShow: true,
		key: 'interceptFrequency',
		type: 'input',
	},
	{
		title: '创建时间',
		noShow: true,
		dataIndex: 'createTime',
		width: 200,
		key: 'createTime',
		type: 'input',
	},
	{
		title: '创建人',
		noShow: true,
		dataIndex: 'createBy',
		key: 'createBy',
		type: 'input',
	},
];
